package com.mashape.p.spoonacularrecipefoodnutritionv1.models;/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Classifiedproduct 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5247382045487235514L;
    private List<String> breadcrumbs;
    private String category;
    private String cleanTitle;
    private int usdaCode;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("breadcrumbs")
    public List<String> getBreadcrumbs ( ) { 
        return this.breadcrumbs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("breadcrumbs")
    public void setBreadcrumbs (List<String> value) { 
        this.breadcrumbs = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("category")
    public String getCategory ( ) { 
        return this.category;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("category")
    public void setCategory (String value) { 
        this.category = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cleanTitle")
    public String getCleanTitle ( ) { 
        return this.cleanTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cleanTitle")
    public void setCleanTitle (String value) { 
        this.cleanTitle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("usdaCode")
    public int getUsdaCode ( ) { 
        return this.usdaCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("usdaCode")
    public void setUsdaCode (int value) { 
        this.usdaCode = value;
    }
 
}
 