package com.mashape.p.spoonacularrecipefoodnutritionv1.models;/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import java.util.*;

public class ClassifiedproductBuilder {
    //the instance to build
    private Classifiedproduct classifiedproduct;

    /**
     * Default constructor to initialize the instance
     */
    public ClassifiedproductBuilder() {
        classifiedproduct = new Classifiedproduct();
    }

    public ClassifiedproductBuilder breadcrumbs(List<String> breadcrumbs) {
        classifiedproduct.setBreadcrumbs(breadcrumbs);
        return this;
    }

    public ClassifiedproductBuilder category(String category) {
        classifiedproduct.setCategory(category);
        return this;
    }

    public ClassifiedproductBuilder cleanTitle(String cleanTitle) {
        classifiedproduct.setCleanTitle(cleanTitle);
        return this;
    }

    public ClassifiedproductBuilder usdaCode(int usdaCode) {
        classifiedproduct.setUsdaCode(usdaCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Classifiedproduct build() {
        return classifiedproduct;
    }
}