package com.mashape.p.spoonacularrecipefoodnutritionv1.models;/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class FindByIngredientsModel 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4799596943246871211L;
    private int id;
    private String image;
    private int likes;
    private int missedIngredientCount;
    private String title;
    private int usedIngredientCount;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("image")
    public String getImage ( ) { 
        return this.image;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("image")
    public void setImage (String value) { 
        this.image = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("likes")
    public int getLikes ( ) { 
        return this.likes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("likes")
    public void setLikes (int value) { 
        this.likes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("missedIngredientCount")
    public int getMissedIngredientCount ( ) { 
        return this.missedIngredientCount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("missedIngredientCount")
    public void setMissedIngredientCount (int value) { 
        this.missedIngredientCount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("usedIngredientCount")
    public int getUsedIngredientCount ( ) { 
        return this.usedIngredientCount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("usedIngredientCount")
    public void setUsedIngredientCount (int value) { 
        this.usedIngredientCount = value;
    }
 
}
 