package com.mashape.p.spoonacularrecipefoodnutritionv1.models;/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import java.util.*;

public class FindByIngredientsModelBuilder {
    //the instance to build
    private FindByIngredientsModel findByIngredientsModel;

    /**
     * Default constructor to initialize the instance
     */
    public FindByIngredientsModelBuilder() {
        findByIngredientsModel = new FindByIngredientsModel();
    }

    public FindByIngredientsModelBuilder id(int id) {
        findByIngredientsModel.setId(id);
        return this;
    }

    public FindByIngredientsModelBuilder image(String image) {
        findByIngredientsModel.setImage(image);
        return this;
    }

    public FindByIngredientsModelBuilder likes(int likes) {
        findByIngredientsModel.setLikes(likes);
        return this;
    }

    public FindByIngredientsModelBuilder missedIngredientCount(int missedIngredientCount) {
        findByIngredientsModel.setMissedIngredientCount(missedIngredientCount);
        return this;
    }

    public FindByIngredientsModelBuilder title(String title) {
        findByIngredientsModel.setTitle(title);
        return this;
    }

    public FindByIngredientsModelBuilder usedIngredientCount(int usedIngredientCount) {
        findByIngredientsModel.setUsedIngredientCount(usedIngredientCount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FindByIngredientsModel build() {
        return findByIngredientsModel;
    }
}