package com.mashape.p.spoonacularrecipefoodnutritionv1.models;/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import java.util.*;

public class ProductjsonBuilder {
    //the instance to build
    private Productjson productjson;

    /**
     * Default constructor to initialize the instance
     */
    public ProductjsonBuilder() {
        productjson = new Productjson();
    }

    public ProductjsonBuilder pluCode(String pluCode) {
        productjson.setPluCode(pluCode);
        return this;
    }

    public ProductjsonBuilder title(String title) {
        productjson.setTitle(title);
        return this;
    }

    public ProductjsonBuilder upc(String upc) {
        productjson.setUpc(upc);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Productjson build() {
        return productjson;
    }
}