package com.mashape.p.spoonacularrecipefoodnutritionv1.models;/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import java.util.*;

public class ProductjsonarrayBuilder {
    //the instance to build
    private Productjsonarray productjsonarray;

    /**
     * Default constructor to initialize the instance
     */
    public ProductjsonarrayBuilder() {
        productjsonarray = new Productjsonarray();
    }

    public ProductjsonarrayBuilder pluCode(String pluCode) {
        productjsonarray.setPluCode(pluCode);
        return this;
    }

    public ProductjsonarrayBuilder title(String title) {
        productjsonarray.setTitle(title);
        return this;
    }

    public ProductjsonarrayBuilder upc(String upc) {
        productjsonarray.setUpc(upc);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Productjsonarray build() {
        return productjsonarray;
    }
}