package com.mashape.p.spoonacularrecipefoodnutritionv1;/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com";

    //The Mashape application you want to use for this session.
    //TODO: Replace the xMashapeKey with an appropriate value
    public static String xMashapeKey = "TODO: Replace";

}
